cp -r "AppDir/app/build.gradle" "Source/Gradle_Scripts/build (1).gradle"
cp -r "AppDir/build.gradle" "Source/Gradle_Scripts/build.gradle"
cp -r "AppDir/gradle.properties" "Source/Gradle_Scripts/gradle (1).properties"

cp -r "AppDir/gradle/wrapper/gradle-wrapper.properties" "Source/Gradle_Scripts/gradle-wrapper.properties"



cp -r "AppDir/settings.gradle" "Source/Gradle_Scripts/settings.gradle"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/FirstClassActivity.java" "Source/java/FirstClassActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/MainActivity.java" "Source/java/MainActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/ProfitActivity.java" "Source/java/ProfitActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/RegisterActivity.java" "Source/java/RegisterActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/SchedActivity.java" "Source/java/SchedActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/ThankYouActivity.java" "Source/java/ThankYouActivity.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/constant/DBConstant.java" "Source/java/constant/DBConstant.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/constant/SQLCommand.java" "Source/java/constant/SQLCommand.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/util/DBOpenHelper.java" "Source/java/util/DBOpenHelper.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/util/DBOperator.java" "Source/java/util/DBOperator.java"
cp -r "AppDir/app/src/main/java/com/example/mis571_finalproject/view/TableView.java" "Source/java/view/TableView.java"
cp -r "AppDir/app/src/main/AndroidManifest.xml" "Source/manifests/AndroidManifest.xml"
cp -r "AppDir/app/src/main/res/layout/firstclass.xml" "Source/res/layout/firstclass.xml"
cp -r "AppDir/app/src/main/res/layout/main_menu.xml" "Source/res/layout/main_menu.xml"
cp -r "AppDir/app/src/main/res/layout/profit.xml" "Source/res/layout/profit.xml"
cp -r "AppDir/app/src/main/res/layout/register.xml" "Source/res/layout/register.xml"
cp -r "AppDir/app/src/main/res/layout/student_sched.xml" "Source/res/layout/student_sched.xml"
cp -r "AppDir/app/src/main/res/layout/thankyou.xml" "Source/res/layout/thankyou.xml"
cp -r "AppDir/app/src/main/res/values/colors.xml" "Source/res/values/colors.xml"
cp -r "AppDir/app/src/main/res/values/strings.xml" "Source/res/values/strings.xml"
cp -r "AppDir/app/src/main/res/values/themes.xml" "Source/res/values/themes.xml"
